services:
  - type: web
    name: aviator-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://aviator-frontend.onrender.com

  - type: web
    name: aviator-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: BACKEND_URL
        value: https://aviator-backend.onrender.com
      - key: VITE_API_URL
        value: https://aviator-backend.onrender.com
      - key: VITE_SOCKET_URL
        value: https://aviator-backend.onrender.com
